name = "QSpaceTools"
uuid = "5cf787ff-debc-4fe4-8ca7-89fdeeb3c098"
version = "1.0.0"
authors = ["James Wrigley <james.wrigley@xfel.eu>"]

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extensions]
QSpaceToolsPythonCallExt = "PythonCall"

[compat]
DimensionalData = "0.30"
HDF5 = "0.17"
OhMyThreads = "0.8"
PythonCall = "0.9"
StaticArrays = "1"

[extras]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PythonCall", "Test"]
